name: alligator
description: Simple Dependency Injector
version: 0.1.0
publish_to: none
homepage: https://mateussiqueira.dev

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  test: ^1.16.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  coverage: ^0.15.2

flutter:
