name: alligator
version: 1.0.0
description: A lightweight and easy-to-use dependency injection library for Dart.
homepage: https://github.com/mateussiqueira/alligator

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"


dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  coverage: ^1.6.3
  test: ^1.22.0

flutter:
