name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Load Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: |
          sudo apt-get install lcov
          flutter test --coverage
          lcov --list coverage/lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
